### PR TITLE
Removes duplicate dependencies in gemspec

### PR DESCRIPTION
**Pull request by mhoofman**
When running a bundle install the following warning is displayed:

```
acts_as_revisionable at /path/to/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/acts_as_revisionable-83b6c4fc81fd did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  duplicate dependency on composite_primary_keys (~> 5, development), (~> 5) use:
    add_runtime_dependency 'composite_primary_keys', '~> 5', '~> 5'
```

This removes the warning.

### CODE REVIEW

**Comment by GerryG** [comment]
Wow, none of those dependencies are needed at all?

Do you also have permissions to merge this?

**Comment by mhoofman** [comment]
They're needed, just repeated in the gemspec. I don't have permission to merge. I think I would need write access to the repo.

**Comment by GerryG** [comment]
Merged.  I think I can send you write permissions.  You want them?

**Comment by mhoofman** [comment]
Sure.

**Pull request merged**
